module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "on-background": "#dfe2eb",
        "on-tertiary-fixed": "#002105",
        secondary: "#c1c7d0",
        "on-primary-fixed-variant": "#004882",
        "surface-variant": "#31353c",
        "on-primary-fixed": "#001c38",
        "on-surface-variant": "#c0c7d4",
        "tertiary-container": "#40ba51",
        background: "#10141a",
        "primary-container": "#58a6ff",
        "on-primary": "#00315c",
        primary: "#a2c9ff",
        error: "#ffb4ab",
        "on-secondary-fixed-variant": "#41474f",
        "on-tertiary-container": "#004411",
        "surface-container-low": "#181c22",
        "outline-variant": "#414752",
        "primary-fixed-dim": "#a2c9ff",
        "surface-tint": "#a2c9ff",
        "primary-fixed": "#d3e4ff",
        "surface-container-lowest": "#0a0e14",
        "on-secondary": "#2b3138",
        "on-error": "#690005",
        "secondary-container": "#41474f",
        "surface-container": "#1c2026",
        "on-primary-container": "#003a6b",
        "secondary-fixed-dim": "#c1c7d0",
        "on-tertiary": "#00390d",
        "surface-container-high": "#262a31",
        outline: "#8b919d",
        "surface-dim": "#10141a",
        "inverse-surface": "#dfe2eb",
        "on-surface": "#dfe2eb",
        "inverse-on-surface": "#2d3137",
        "on-tertiary-fixed-variant": "#005317",
        "surface-container-highest": "#31353c",
        "tertiary-fixed-dim": "#67df70",
        tertiary: "#67df70",
        "tertiary-fixed": "#83fc89",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#161c23",
        "surface-bright": "#353940",
        "inverse-primary": "#0060aa",
        surface: "#10141a",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["JetBrains Mono"],
      },
    },
  },
  plugins: [],
}
